# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import product_pb2 as product__pb2


class ProductServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateProduct = channel.unary_unary(
                '/product.ProductService/CreateProduct',
                request_serializer=product__pb2.CreateProductRequest.SerializeToString,
                response_deserializer=product__pb2.CreateProductResponse.FromString,
                )
        self.GetProduct = channel.unary_unary(
                '/product.ProductService/GetProduct',
                request_serializer=product__pb2.GetProductRequest.SerializeToString,
                response_deserializer=product__pb2.GetProductResponse.FromString,
                )
        self.UpdateProduct = channel.unary_unary(
                '/product.ProductService/UpdateProduct',
                request_serializer=product__pb2.UpdateProductRequest.SerializeToString,
                response_deserializer=product__pb2.UpdateProductResponse.FromString,
                )
        self.DeleteProduct = channel.unary_unary(
                '/product.ProductService/DeleteProduct',
                request_serializer=product__pb2.DeleteProductRequest.SerializeToString,
                response_deserializer=product__pb2.DeleteProductResponse.FromString,
                )
        self.ListProducts = channel.unary_unary(
                '/product.ProductService/ListProducts',
                request_serializer=product__pb2.ListProductsRequest.SerializeToString,
                response_deserializer=product__pb2.ListProductsResponse.FromString,
                )
        self.GetProductsByUser = channel.unary_unary(
                '/product.ProductService/GetProductsByUser',
                request_serializer=product__pb2.GetProductsByUserRequest.SerializeToString,
                response_deserializer=product__pb2.GetProductsByUserResponse.FromString,
                )


class ProductServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateProduct(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetProduct(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateProduct(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteProduct(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListProducts(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetProductsByUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ProductServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateProduct': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateProduct,
                    request_deserializer=product__pb2.CreateProductRequest.FromString,
                    response_serializer=product__pb2.CreateProductResponse.SerializeToString,
            ),
            'GetProduct': grpc.unary_unary_rpc_method_handler(
                    servicer.GetProduct,
                    request_deserializer=product__pb2.GetProductRequest.FromString,
                    response_serializer=product__pb2.GetProductResponse.SerializeToString,
            ),
            'UpdateProduct': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateProduct,
                    request_deserializer=product__pb2.UpdateProductRequest.FromString,
                    response_serializer=product__pb2.UpdateProductResponse.SerializeToString,
            ),
            'DeleteProduct': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteProduct,
                    request_deserializer=product__pb2.DeleteProductRequest.FromString,
                    response_serializer=product__pb2.DeleteProductResponse.SerializeToString,
            ),
            'ListProducts': grpc.unary_unary_rpc_method_handler(
                    servicer.ListProducts,
                    request_deserializer=product__pb2.ListProductsRequest.FromString,
                    response_serializer=product__pb2.ListProductsResponse.SerializeToString,
            ),
            'GetProductsByUser': grpc.unary_unary_rpc_method_handler(
                    servicer.GetProductsByUser,
                    request_deserializer=product__pb2.GetProductsByUserRequest.FromString,
                    response_serializer=product__pb2.GetProductsByUserResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'product.ProductService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ProductService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateProduct(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/product.ProductService/CreateProduct',
            product__pb2.CreateProductRequest.SerializeToString,
            product__pb2.CreateProductResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetProduct(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/product.ProductService/GetProduct',
            product__pb2.GetProductRequest.SerializeToString,
            product__pb2.GetProductResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdateProduct(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/product.ProductService/UpdateProduct',
            product__pb2.UpdateProductRequest.SerializeToString,
            product__pb2.UpdateProductResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteProduct(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/product.ProductService/DeleteProduct',
            product__pb2.DeleteProductRequest.SerializeToString,
            product__pb2.DeleteProductResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListProducts(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/product.ProductService/ListProducts',
            product__pb2.ListProductsRequest.SerializeToString,
            product__pb2.ListProductsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetProductsByUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/product.ProductService/GetProductsByUser',
            product__pb2.GetProductsByUserRequest.SerializeToString,
            product__pb2.GetProductsByUserResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
